name = "openwok"
main = "crates/worker/build/worker/shim.mjs"
compatibility_date = "2024-12-01"

# [build]
# command = "./scripts/build-worker.sh"

[assets]
directory = "public"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "openwok-db"
database_id = "a330a315-d6ee-42b0-a206-99cad54a7744"
migrations_dir = "migrations"

[vars]
ENVIRONMENT = "production"

# Dev overrides
[env.dev]
name = "openwok-dev"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "openwok-db-dev"
database_id = ""
migrations_dir = "migrations"
