[application]
# Disable hot-reload in prod to avoid ws connection error
name = "openwok"
asset_dir = "public"

[web.app]
title = "OpenWok — Fair Food Delivery"

[web.resource]
style = ["./tailwind.css", "./style.css"]

[web.resource.dev]
style = []
script = []

[web.watcher]
reload_html = true
watch_path = ["src"]
index_on_404 = true

[bundle]
identifier = "co.superduperai.openwok"
publisher = "SuperDuperAI"
